name: GitHub Actions Check
run-name: ${{ github.actor }} Checks ğŸš€
on: [push, pull_request]
jobs:
  Link-Format-Checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: scripts/link-format-chk.sh
  Build-Table-Checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: scripts/buildtable.pl >/tmp/table.mediawiki || exit 1
  Diff-Checks:
    name: "Diff Checks (fails until number assignment)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - run: scripts/diffcheck.sh
  Typo-Checks:
    name: "Typo Checks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4

      - name: Check spelling
        uses: crate-ci/typos@master
            - nazwa: Konfiguracja Java JDK
  uÅ¼ywa: actions/setup-java@v4.7.0
  z:
    # Wersja Java do skonfigurowania. Przyjmuje caÅ‚Ä… lub semver wersjÄ™ Java. Zobacz przykÅ‚ady obsÅ‚ugiwanej skÅ‚adni w pliku README
    java-version: # opcjonalnie
    # ÅšcieÅ¼ka do pliku `.java-version`. Zobacz przykÅ‚ady obsÅ‚ugiwanej skÅ‚adni w pliku README
    java-version-file: # opcjonalnie
    # Dystrybucja Java. Zobacz listÄ™ obsÅ‚ugiwanych dystrybucji w pliku README
    dystrybucja:
    # Typ pakietu (jdk, jre, jdk+fx, jre+fx)
    java-package: # opcjonalny, domyÅ›lnie jdk
    # Architektura pakietu (domyÅ›lnie architektura programu uruchamiajÄ…cego akcjÄ™)
    architektura: # opcjonalnie
    # ÅšcieÅ¼ka do miejsca, w ktÃ³rym znajduje siÄ™ skompresowany JDK
    jdkFile: # opcjonalnie
    # Ustaw tÄ™ opcjÄ™, jeÅ›li chcesz, aby akcja sprawdzaÅ‚a, czy jest dostÄ™pna najnowsza wersja speÅ‚niajÄ…ca specyfikacjÄ™ wersji
    sprawdÅº-najnowsze: #opcjonalne
    # ID repozytorium distributionManagement w pliku pom.xml. DomyÅ›lnie `github`
    server-id: # opcjonalnie, domyÅ›lnie jest to github
    # Nazwa zmiennej Å›rodowiskowej dla nazwy uÅ¼ytkownika do uwierzytelniania w repozytorium Apache Maven. DomyÅ›lnie jest to $GITHUB_ACTOR
    server-username: # opcjonalnie, domyÅ›lnie GITHUB_ACTOR
    # Nazwa zmiennej Å›rodowiskowej dla hasÅ‚a lub tokenu do uwierzytelniania w repozytorium Apache Maven. DomyÅ›lnie jest to $GITHUB_TOKEN
    server-password: # opcjonalne, domyÅ›lnie GITHUB_TOKEN
    # ÅšcieÅ¼ka do miejsca, w ktÃ³rym zostanie zapisany plik settings.xml. DomyÅ›lnie jest to ~/.m2.
    Å›cieÅ¼ka-ustawieÅ„: # opcjonalnie
    # Nadpisz plik settings.xml, jeÅ›li istnieje. DomyÅ›lnie jest to â€trueâ€.
    overwrite-settings: # opcjonalne, domyÅ›lnie true
    # Klucz prywatny GPG do zaimportowania. DomyÅ›lnie jest to pusty ciÄ…g.
    gpg-private-key: # opcjonalny
    # Nazwa zmiennej Å›rodowiskowej dla hasÅ‚a klucza prywatnego GPG. DomyÅ›lnie jest to $GPG_PASSPHRASE.
    gpg-passphrase: # opcjonalnie
    # Nazwa platformy kompilacji do buforowania zaleÅ¼noÅ›ci. MoÅ¼e to byÄ‡ â€mavenâ€, â€gradleâ€ lub â€sbtâ€.
    pamiÄ™Ä‡ podrÄ™czna: # opcjonalnie
    # ÅšcieÅ¼ka do pliku zaleÅ¼noÅ›ci: pom.xml, build.gradle, build.sbt itd. Ta opcja moÅ¼e byÄ‡ uÅ¼ywana z opcjÄ… `cache`. JeÅ›li ta opcja jest pominiÄ™ta, akcja wyszukuje pliku zaleÅ¼noÅ›ci w caÅ‚ym repozytorium. Ta opcja obsÅ‚uguje symbole wieloznaczne i listÄ™ nazw plikÃ³w do buforowania wielu zaleÅ¼noÅ›ci.
    Å›cieÅ¼ka-zaleÅ¼noÅ›ci-pamiÄ™ci-podrÄ™cznej: # opcjonalnie
    # ObejÅ›cie umoÅ¼liwiajÄ…ce przekazanie statusu zadania do kroku post job. Ta zmienna nie jest przeznaczona do rÄ™cznego ustawiania
    job-status: # opcjonalny, domyÅ›lnie ${{ job.status }}
    # Token uÅ¼ywany do uwierzytelniania podczas pobierania manifestÃ³w wersji hostowanych na github.com, takich jak kompilacja Microsoft Build of OpenJDK. Podczas uruchamiania tej akcji na github.com, wartoÅ›Ä‡ domyÅ›lna jest wystarczajÄ…ca. Podczas uruchamiania na GHES, moÅ¼esz przekazaÄ‡ osobisty token dostÄ™pu dla github.com, jeÅ›li wystÄ™puje ograniczenie szybkoÅ›ci.
    token: # opcjonalny, domyÅ›lnie ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # Nazwa identyfikatora Maven Toolchain, jeÅ›li domyÅ›lna nazwa â€${distribution}_${java-version}â€ nie jest poÅ¼Ä…dana. Zobacz przykÅ‚ady obsÅ‚ugiwanej skÅ‚adni w pliku Advanced Usage
    mvn-toolchain-id: # opcjonalnie
    # Nazwa dostawcy Maven Toolchain, jeÅ›li domyÅ›lna nazwa â€${distribution}â€ nie jest poÅ¼Ä…dana. Zobacz przykÅ‚ady obsÅ‚ugiwanej skÅ‚adni w pliku Advanced Usage
    mvn-toolchain-vendor: # opcjonalny

          
